### ISSUE TITLE
Release a new version.

### ISSUE THREAD

**Issue by davidCarlos** [douban/PyCharlockHolmes#8]
Could you please, release a new version of PyCharlockHolmes with the support to python3?

**Comment by liluo** [comment]
@xtao

**Comment by GesielFreitas** [comment]
@xtao ajuda ai please!!

**Comment by adailson2** [comment]
We need the new version, help us please

**Comment by Jullianaa** [comment]
Hey, do you intend to launch a new release?

**Comment by xtao** [comment]
I'll release this in two weeks.

**Comment by xtao** [comment]
See: https://pypi.org/project/charlockholmes
